<?php

/**
 * PluginStudentParentInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginStudentParentInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginStudentParentInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginStudentParentInformation');
    }
}