<?php

/**
 * PluginTestTable2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTestTable2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTestTable2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTestTable2');
    }
}