<?php

/**
 * PluginTestTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTestTableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTestTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTestTable');
    }
}