<?php

/**
 * TestTable2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestTable2Table extends PluginTestTable2Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestTable2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestTable2');
    }
}