<?php

/**
 * TestTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestTableTable extends PluginTestTableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestTable');
    }
}