index:
  credentials:  [[Admin, Supervisor, Manager]]

ListDefineKpi:
  credentials:  [Admin]
  
SaveKpi:
  credentials:  [Admin]

UpdateKpi:
  credentials:  [Admin]
  
CopyKpi:
  credentials:  [Admin]
  
DeleteDefineKpi:
  credentials:  [Admin]
 
SaveReview:
  credentials:  [Admin]
