<?php

/**
 * BaseTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $studentId
 * @property int $momMobileNo
 * @property int $dadMobileNo
 * 
 * @method int       getStudentId()   Returns the current record's "studentId" value
 * @method int       getMomMobileNo() Returns the current record's "momMobileNo" value
 * @method int       getDadMobileNo() Returns the current record's "dadMobileNo" value
 * @method TestTable setStudentId()   Sets the current record's "studentId" value
 * @method TestTable setMomMobileNo() Sets the current record's "momMobileNo" value
 * @method TestTable setDadMobileNo() Sets the current record's "dadMobileNo" value
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestTable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test_table');
        $this->hasColumn('student_id as studentId', 'int', 2000000, array(
             'type' => 'int',
             'autoincrement' => true,
             'primary' => true,
             'length' => 2000000,
             ));
        $this->hasColumn('mother_contact_mobile as momMobileNo', 'int', 10, array(
             'type' => 'int',
             'length' => 10,
             ));
        $this->hasColumn('father_contact_number_mobile as dadMobileNo', 'int', 10, array(
             'type' => 'int',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}